name: K3s setup

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  TOKEN_FILE: /var/lib/rancher/k3s/server/node-token
  
jobs:
  setup-master:
    runs-on: ubuntu-latest

    steps:
    - name: Download k3s
      run: |
        curl -sfL https://get.k3s.io | sh -
        export MASTER_IP=`hostname -I | cut -d " " -f 1`
        export TOKEN=`sudo cat $TOKEN_FILE`
        echo "master_ip=$MASTER_IP" >> $GITHUB_ENV
        echo "token=$TOKEN" >> $GITHUB_ENV

  setup-nodes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [n1, n2, n3, n4]
    
    steps:
    - name: Setup nodes
      run: |
        curl -sfL https://get.k3s.io | K3S_URL=https://${{ env.master_ip }}:6443 K3S_TOKEN=${{ env.token }} K3S_NODE_NAME=${{ matrix.node }} sh -
        sudo kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml -n kube-system get endpoints
        
