name: terraform

on:
  workflow_dispatch:

env:
  AWS_ACCESS_ID : ${{ secrets.AWS_ACCESS_ID }}
  AWS_SECRET_KEY : ${{ secrets.AWS_SECRET_KEY }}
  
jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
    
    - id: step1
      run: terraform -version
