name: terraform

on:
  workflow_dispatch:

env:
  AWS_ACCESS_ID : ${{ secrets.AWS_ACCESS_ID }}
  AWS_SECRET_KEY : ${{ secrets.AWS_SECRET_KEY }}
  
jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
    
    - name: Install AWS CLI
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt -y install awscli
        aws --version
        export AWS_ACCESS_KEY_ID="$AWS_ACCESS_ID"
        export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_KEY"
    
    - name: Get TF version
      working-directory: terraform
      run: |
        terraform ftm -check
        terraform fmt -diff
        terraform init
        terraform validate
        terraform plan
      continue-on-error: true
        
