name: K3s setup

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  TOKEN_FILE: /var/lib/rancher/k3s/server/node-token
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download k3s
      run: |
        curl -sfL https://get.k3s.io | sh -
        export MASTER_IP=`hostname -I | cut -d " " -f 1`
        export TOKEN=`sudo cat $TOKEN_FILE`
        echo "master_ip=$MASTER_IP" >> $GITHUB_ENV
        echo "token=$TOKEN" >> $GITHUB_ENV
        curl -sfL https://get.k3s.io | K3S_URL=https://$MASTER_IP:6443 K3S_TOKEN=$TOKEN sh -
        sudo kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml -n kube-system get endpoints
        
