name: terraform

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_ID }}
  AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_KEY }}
  
jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
    
    - name: Update and install AWS CLI
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt -y install awscli
        aws --version
        export AWS_ACCESS_KEY_ID
        export AWS_SECRET_ACCESS_KEY
    
    - name: Apply Terraform
      working-directory: terraform
      run: |
        terraform fmt -diff
        terraform init
        terraform validate
        terraform plan

    - name: Sleep and destroy
      working-directory: terraform
      run: |
        date
        sleep 60
        date
        terraform destroy -auto-approve -input=false
