name: K3s setup

on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download k3s
      run: |
        curl -sfL https://get.k3s.io | sh -
        ls -lh /etc/rancehr/k3s/
        sudo kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml -n kube-system get pods
