name: terraform

on:
  workflow_dispatch:

env:
  AWS_ACCESS_ID : ${{ secrets.AWS_ACCESS_ID }}
  AWS_SECRET_KEY : ${{ secrets.AWS_SECRET_KEY }}

jobs:

  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Terra
      - uses: actions/checkout@v3, hashicorp/setup-terraform@v2
      - run: terraform -version
        

        
