name: aws-nuke

on:
  workflow_dispatch:

env:
  NUKE_URL : "https://github.com/rebuy-de/aws-nuke/releases/download/v2.19.0/aws-nuke-v2.19.0-linux-amd64.tar.gz"
  AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_ID }}
  AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_KEY }}
  
jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Update and install AWS-CLI, aws-nuke
      run: |
        export AWS_ACCESS_KEY_ID
        export AWS_SECRET_ACCESS_KEY
        sudo apt update
        sudo apt upgrade
        sudo apt -y install awscli
        aws --version
        aws sts get-caller-identity --output text --debug true
        #wget -qc ${NUKE_URL} -O - | tar -xz
        #mv ./aws-nuke-* ./aws-nuke
        #./aws-nuke --access-key-id ${AWS_ACCESS_KEY_ID} --secret-access-key ${AWS_SECRET_ACCESS_KEY}
