name: K3s setup

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download k3s
      run: |
        curl -sfL https://get.k3s.io | sh -
        sudo systemctl status k3s
        echo "master_ip=`hostname -i`" >> $GITHUB_ENV
        sudo kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml -n kube-system get endpoints
        echo "Master IP: ${{ env.master_ip }}"
