name: terraform

on:
  workflow_dispatch:

jobs:
  runs-on: ubuntu-latest
  uses: actions/checkout@v3, hashicorp/setup-terraform@v2
  env:
    AWS_ACCESS_ID : ${{ secrets.AWS_ACCESS_ID }}
    AWS_SECRET_KEY : ${{ secrets.AWS_SECRET_KEY }}
    
  step:
    - name: Terraform version
      run: terraform -version
        

        
