name: K3s setup

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  TOKEN_FILE: /var/lib/rancher/k3s/server/node-token
  
jobs:
  setup-master:
    runs-on: ubuntu-latest
    
    outputs:
      master_ip: ${{steps.step1.outputs.master_ip}}
      token: ${{steps.step1.outputs.token}}

    steps:
    - name: Download k3s
      id: step1
      run: |
        curl -sfL https://get.k3s.io | sh -
        export MASTER_IP=`hostname -I | cut -d " " -f 1`
        export TOKEN=`sudo cat $TOKEN_FILE`
        echo "::set-output name=master_ip::$MASTER_IP"
        echo "::set-output name=token::$TOKEN"

  setup-nodes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [n1, n2, n3, n4]
    
    steps:
    - name: Setup nodes
      run: |
        curl -sfL https://get.k3s.io | K3S_URL=https://${{ needs.setup-master.outputs.master_ip }}:6443 K3S_TOKEN=${{ needs.setup-master.outputs.token }} K3S_NODE_NAME=${{ matrix.node }} sh -
        sudo kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml -n kube-system get endpoints
        
