name: K3s setup

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  MASTER_TOKEN: /var/lib/rancher/k3s/server/node-token
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download k3s
      run: |
        curl -sfL https://get.k3s.io | sh -
        sudo systemctl status k3s
        MASTER_IP=`hostname -I | cut -d " " -f 1`
        echo "master_ip=`hostname -I | cut -d ' ' -f 1`" >> $GITHUB_ENV
        cat $MASTER_TOKEN
        sudo kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml -n kube-system get endpoints
        echo "Master IP: $MASTER_IP"
